// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Conference struct {
	ID        uuid.UUID
	Title     string
	Date      time.Time
	Location  string
	Website   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	CreatedBy uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ConferenceRegistration struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConferenceID uuid.UUID
	Status       string
	Role         string
	Notes        sql.NullString
	NeedsRide    sql.NullBool
	HasCar       sql.NullBool
	RegisteredAt sql.NullTime
	CancelledAt  sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Name      string
	Nickname  sql.NullString
	City      sql.NullString
	AvatarUrl sql.NullString
	Bio       sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	CreatedAt  sql.NullTime
	LastUsedAt sql.NullTime
	Revoked    bool
}
