// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Conference struct {
	ID        uuid.UUID
	Title     string
	Date      time.Time
	Location  string
	Website   *string
	Latitude  *float64
	Longitude *float64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConferenceRegistration struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConferenceID uuid.UUID
	Status       string
	Role         string
	Notes        *string
	NeedsRide    bool
	HasCar       bool
	RegisteredAt time.Time
	CancelledAt  *time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Name      string
	Nickname  *string
	City      *string
	AvatarUrl *string
	Bio       *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	Revoked    bool
}

type UserRole string

const (
	RoleAttendee  UserRole = "attendee"
	RoleOrganizer UserRole = "organizer"
	RoleSpeaker   UserRole = "speaker"
	RoleVolunteer UserRole = "volunteer"
)

type RegistrationStatus string

const (
	StatusRegistered RegistrationStatus = "registered"
	StatusWaitlist   RegistrationStatus = "waitlist"
	StatusCancelled  RegistrationStatus = "cancelled"
	StatusAttended   RegistrationStatus = "attended"
)
