// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CancelRegistration(ctx context.Context, id uuid.UUID) (ConferenceRegistration, error)
	CreateConference(ctx context.Context, arg CreateConferenceParams) (Conference, error)
	// Token management queries (user_tokens table must be present in schema.sql)
	CreateToken(ctx context.Context, arg CreateTokenParams) (UserToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllConferences(ctx context.Context) error
	DeleteAllRegistrations(ctx context.Context) error
	DeleteAllUsers(ctx context.Context) error
	DeleteConference(ctx context.Context, id uuid.UUID) error
	DeleteRegistration(ctx context.Context, arg DeleteRegistrationParams) error
	DeleteToken(ctx context.Context, id uuid.UUID) error
	GetConferenceByID(ctx context.Context, id uuid.UUID) (Conference, error)
	GetConferenceStats(ctx context.Context, id uuid.UUID) (GetConferenceStatsRow, error)
	GetRegistration(ctx context.Context, arg GetRegistrationParams) (ConferenceRegistration, error)
	GetRegistrationsByConference(ctx context.Context, conferenceID uuid.UUID) ([]GetRegistrationsByConferenceRow, error)
	GetRegistrationsByUser(ctx context.Context, userID uuid.UUID) ([]GetRegistrationsByUserRow, error)
	GetTokenByHash(ctx context.Context, tokenHash string) (UserToken, error)
	GetTokensByUser(ctx context.Context, userID uuid.UUID) ([]UserToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListConferences(ctx context.Context) ([]Conference, error)
	ListConferencesByLocation(ctx context.Context, location string) ([]Conference, error)
	ListUpcomingConferences(ctx context.Context) ([]Conference, error)
	ListUsersNeedingRide(ctx context.Context, conferenceID uuid.UUID) ([]ListUsersNeedingRideRow, error)
	ListUsersOfferingRide(ctx context.Context, conferenceID uuid.UUID) ([]ListUsersOfferingRideRow, error)
	RegisterUserToConference(ctx context.Context, arg RegisterUserToConferenceParams) (ConferenceRegistration, error)
	RevokeToken(ctx context.Context, id uuid.UUID) (UserToken, error)
	UpdateConference(ctx context.Context, arg UpdateConferenceParams) (Conference, error)
	UpdateRegistrationStatus(ctx context.Context, arg UpdateRegistrationStatusParams) (ConferenceRegistration, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
